### ISSUE TITLE
`<meta>` Array entry does not overidden

### ISSUE THREAD

**Issue by harlan-zw** [unjs/unhead#12]
### Describe the bug

app.vue

```ts
 useHead({
      meta: [
        {
          property: 'og:image',
          content: [
            'https://cdn.example.com/image.jpg',
            'https://cdn.example.com/image2.jpg',
          ]
        }
      ]
    })
```

// page
```ts
    useHead({
      meta: [
        {
          property: 'og:image',
          content:  'https://cdn.example.com/new.jpg',
        },
      ]
    })
```

It only replaces one of the metas

### System Info

```Shell
n/a
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tvld** [comment]
Same issue here...  Seems like when page is loaded it does not change the meta's.  ``title`` works
