### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by harlan-zw** [unjs/unhead#395]
## Documentation

- [x] https://github.com/unjs/unhead/pull/460: Refresh UI, Redo most of the content - https://unhead-unjs-io.nuxt.dev/
- [x] https://github.com/unjs/unhead/discussions/431 Recipe: Add tailwind merge example

### Migration

- [x] https://github.com/nuxt/nuxt/pull/30579: Nuxt Migration PR
- [x] https://github.com/unjs/unhead/blob/main/docs/migration.md: v1 -> v2 Migration guide

## :zap: Performance

- [x] https://github.com/unjs/unhead/pull/504
- [x]  :warning: https://github.com/unjs/unhead/pull/448
- [x] https://github.com/unjs/unhead/pull/451
- [x] ⚠ https://github.com/unjs/unhead/pull/488
- [x] ⚠  https://github.com/unjs/unhead/pull/493
- [x] ⚠ https://github.com/unjs/unhead/pull/494

## :rocket: Features

- [ ] https://github.com/unjs/unhead/issues/455: Add way to access resolved titles
- [x] https://github.com/unjs/unhead/pull/479: Default critical tags (charset, viewport, lang)
- [x] https://github.com/unjs/unhead/pull/473: Extract existing tags from SSR templates
- [x] :warning: https://github.com/unjs/unhead/pull/459: Requires all `unhead` composables to have `head` as first arg
- [x]  :warning:  https://github.com/unjs/unhead/pull/437: Drop `activeHead` & `setHeadInjectionHandler`
- [x]  :warning: https://github.com/unjs/unhead/pull/440: Capo by default
- [x] https://github.com/unjs/unhead/pull/443: Functions as input that can resolve as undefined or null
- [x] https://github.com/unjs/unhead/pull/489
- [x] https://github.com/unjs/unhead/pull/490
- [x] https://github.com/unjs/unhead/pull/492

## 🐛 Bugs

- [x] https://github.com/unjs/unhead/pull/475

## :broom:  Deprecation Removals

- [x]  :warning: https://github.com/unjs/unhead/pull/444
- [x] :warning: https://github.com/unjs/unhead/pull/445: Drop support for promises as input
- [x] :warning: https://github.com/unjs/unhead/pull/447: Drop support for `vmid`, `hid` dedupe keys and  `children`, `body`
- [x]  :warning:  https://github.com/unjs/unhead/pull/439: Drop Vue 2 support

## :broom: Chore / Deprecations

- [x] https://github.com/unjs/unhead/pull/505
- [x] https://github.com/unjs/unhead/pull/449
- [x] https://github.com/unjs/unhead/pull/483
- [x] https://github.com/unjs/unhead/pull/484
- [x] ⚠ https://github.com/unjs/unhead/pull/482

## :dart: Stretch Goals

- [x] https://github.com/unjs/unhead/pull/500: Solid support
  - [x] `@unhead/solid-js`
  - [x] [Install Docs](https://unhead-unjs-io.nuxt.dev/docs/solid-js/installation)
  - [x] useScript
  - [x] useSchemaOrg
  - [x]  Usage Docs
- [x] https://github.com/unjs/unhead/pull/477: React support
  - [x] `@unhead/react`
  - [x] [Install Docs](https://unhead-unjs-io.nuxt.dev/docs/react/installation)
  - [x] useScript
  - [x] useSchemaOrg
  - [x]  Usage Docs
- [x] https://github.com/unjs/unhead/pull/452: Svelte support
  - [x] `@unhead/svelte`
  - [x] [Install Docs](https://unhead-unjs-io.nuxt.dev/docs/svelte/installation)
  - [x] useScript
  - [x] useSchemaOrg
  - [x]  Usage Docs
- [x] https://github.com/unjs/unhead/pull/467 Angular Support
  - [x] `@unhead/angular`
  - [x] [Install Docs](https://unhead-unjs-io.nuxt.dev/docs/svelte/installation)
  - [x] useScript
  - [x] useSchemaOrg
  - [x]  Usage Docs

**Comment by TechAkayy** [comment]
Please add `twitter:url` to the list of twitter meta tags.

**Comment by harlan-zw** [comment]
> Please add `twitter:url` to the list of twitter meta tags.

I believe this was never implemented as it's not documented by the [Twitter docs](https://developer.x.com/en/docs/x-for-websites/cards/guides/getting-started). If you think this is a mistake please make a new issue, I would consider it a bug if it is documented.
